Remove all dead legacy code
dnsimple/chef-exabgp pull request #17
Opened 2017-10-18 12:11 UTC by jmauro

Hello,

Since those template are not used anymore, we could remove those, don't you think?

Regards,
JM

2017-10-23 21:52 UTC, martinisoft requested changes
I can agree on the majority of these changes, but the template for the config needs to stay for sure. I'd like to make a failing test case for this too.

2017-10-23 21:52 UTC, martinisoft commented on templates/default/exabgp.conf.erb
> -neighbor 127.0.0.1 {
This template is still required as a default: https://github.com/dnsimple/chef-exabgp/blob/5ab6b6fc03deeab874273ea99488fe890e7d569b/resources/exabgp.rb#L34

2017-10-23 21:52 UTC, martinisoft commented on templates/default/exabgp.conf.erb
> -neighbor 127.0.0.1 {
The fact you removed it without a test breaking reveals a regression we should be covering in our test cases.

2017-10-25 00:12 UTC, jmauro commented
Hello @martinisoft, I leave the default template alone and add a default cookbook source for the custom resource.

Let me know if this does the job

Regards,
JM

2017-12-21 22:02 UTC, onlyhavecans approved these changes

2018-02-12 16:37 UTC, martinisoft approved these changes

2018-02-12 16:37 UTC, merged